# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelProyecto', models.CharField(max_length=70)),
                ('tipo', models.CharField(max_length=30)),
                ('ubicacion', models.URLField(max_length=300)),
                ('dispositivo', models.CharField(max_length=50)),
                ('caracteristicas', models.CharField(max_length=400)),
                ('topePresupuestal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagoPorBug', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
