# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='dispositivo',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOVIL', 'Movil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOVIL', 'Movil')], max_length=30),
        ),
    ]
