# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20181209_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='dispositivo',
            field=models.CharField(choices=[('Computadora', 'Computadora'), ('Smartphone', 'Smartphone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Web', 'Web'), ('Movil', 'Movil')], max_length=30),
        ),
    ]
