# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('user_type', models.CharField(choices=[('TESTER', 'Tester'), ('CLIENT', 'Client')], max_length=30, verbose_name='User Type')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation Date')),
                ('updated_date', models.DateField(default=datetime.date.today, verbose_name='Updated Date')),
            ],
            options={
                'ordering': ['username'],
                'db_table': 'tb_user',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
