# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
