# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_tb_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_user',
            name='avatar',
        ),
    ]
