# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20181212_2008'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='device',
        ),
        migrations.AddField(
            model_name='project',
            name='device',
            field=models.ManyToManyField(to='Devices.Device'),
        ),
    ]
