# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20181217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='device',
            field=models.ManyToManyField(related_name='Device', to='Devices.Device'),
        ),
    ]
