# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20181217_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pause', 'Pause'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
