# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_functionality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionality',
            options={'verbose_name_plural': 'Functionalities'},
        ),
    ]
