# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Smartphone', 'Smartphone')], max_length=30)),
                ('os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac OS', 'Mac OS'), ('Android', 'Android'), ('IOS', 'IOS')], max_length=50)),
                ('version', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
