# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Smartphone', 'Smartphone')], max_length=30)),
                ('os', models.CharField(choices=[('Computer', 'Computer'), ('Smartphone', 'Smartphone')], max_length=50)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
