# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20181212_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
