# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionality_id', models.IntegerField(verbose_name='Functionality ID')),
                ('device_id', models.IntegerField(verbose_name='Device ID')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation Date')),
                ('updated_date', models.DateField(default=datetime.date.today, verbose_name='Updated Date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
