# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0004_auto_20190115_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Test Decription'),
            preserve_default=False,
        ),
    ]
