# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0005_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='funcionality_id',
            new_name='functionality_id',
        ),
    ]
