# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeDispositivo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Computadora', 'Computadora'), ('Smartphone', 'Smartphone')], max_length=30)),
                ('sistemaOperativo', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac'), ('Android', 'Android'), ('IOS', 'IOS')], max_length=50)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
