# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='nombreDeDispositivo',
            new_name='nombreDelDispositivo',
        ),
    ]
