# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
