# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0003_auto_20181129_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
