# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0006_tbuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbUser',
        ),
    ]
