# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0008_tb_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_user',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
