# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0010_auto_20181210_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='user_type',
            field=models.CharField(choices=[('TESTER', 'Tester'), ('CLIENT', 'Client')], max_length=30),
        ),
    ]
