# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0011_auto_20181210_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='tb_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tb_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tb_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tb_user',
            name='password',
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
