# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0012_auto_20181210_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_user',
            name='enabled',
        ),
    ]
