# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0013_remove_tb_user_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='state',
            field=models.CharField(max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='updated_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='user_type',
            field=models.CharField(choices=[('TESTER', 'Tester'), ('CLIENT', 'Client')], max_length=30, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterModelTable(
            name='tb_user',
            table='Tb_user',
        ),
    ]
