# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0014_auto_20181211_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_user',
            table='tb_user',
        ),
    ]
