# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBridgeApp', '0015_auto_20181211_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_user',
        ),
    ]
