# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11 on 2019-02-06 00:19
=======
# Generated by Django 1.11 on 2019-01-29 06:39
>>>>>>> 1e76af9444df3aa6779f6bd26b224af9d9dea43c
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_found', models.CharField(max_length=500, verbose_name='Error Found')),
                ('steps', models.CharField(max_length=2000, verbose_name='Steps')),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshots/')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation Date')),
                ('updated_date', models.DateField(default=datetime.date.today, verbose_name='Updated Date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('test_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Tests.Test', verbose_name='Test')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['test_id'],
                'db_table': 'bug',
                'verbose_name_plural': 'Bugs',
            },
        ),
    ]
