# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(verbose_name='Test')),
                ('error_found', models.CharField(max_length=500, verbose_name='Error Found')),
                ('steps', models.CharField(max_length=2000, verbose_name='Steps')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation Date')),
                ('updated_date', models.DateField(default=datetime.date.today, verbose_name='Updated Date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'ordering': ['test_id'],
                'db_table': 'bug',
                'verbose_name_plural': 'Bugs',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionality_id', models.IntegerField(verbose_name='Functionality')),
                ('device_id', models.IntegerField(verbose_name='Device')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation Date')),
                ('updated_date', models.DateField(default=datetime.date.today, verbose_name='Updated Date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
