# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(max_length=255, upload_to='screenshots/'),
        ),
    ]
