# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
