# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bugs', '0002_auto_20190108_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='test_id',
            field=models.IntegerField(verbose_name='Test ID'),
        ),
    ]
