# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bugs', '0003_auto_20190115_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='test_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Tests.Test'),
        ),
    ]
