# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bugs', '0005_auto_20190122_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
