# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0002_remove_functionality_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='device',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
